import fs from "node:fs";
import path from "node:path";

// The framework-owned known-good toolchain matrix. roblox-ts pins the exact
// TypeScript version it can drive, so the starter ships the pair together —
// `aruna doctor` re-checks the pairing later (its toolchain skew warning).
// Keep in sync with apps/rbxts-harness/package.json in the aruna workspace.
export const PINNED_TOOLCHAIN: Record<string, string> = {
  "@rbxts/compiler-types": "3.0.0-types.0",
  "@rbxts/types": "^1.0.924",
  "roblox-ts": "3.0.0",
  typescript: "5.5.3",
};

export const ROKIT_ROJO_SPEC = "rojo-rbx/rojo@7.7.0";

export type PackageManager = "npm" | "pnpm" | "yarn" | "bun";

// `npm create aruna-app` (and the pnpm/yarn/bun equivalents) sets
// npm_config_user_agent to "<pm>/<version> ...", which is the only reliable
// signal for which package manager the user invoked.
export function detectPackageManager(userAgent: string | undefined): PackageManager {
  if (userAgent === undefined) {
    return "npm";
  }
  if (userAgent.startsWith("pnpm/")) {
    return "pnpm";
  }
  if (userAgent.startsWith("yarn/")) {
    return "yarn";
  }
  if (userAgent.startsWith("bun/")) {
    return "bun";
  }
  return "npm";
}

export function installCommand(pm: PackageManager): { command: string; args: string[] } {
  return pm === "yarn" ? { command: "yarn", args: [] } : { command: pm, args: ["install"] };
}

// npm package name rules, minus scopes — the scaffolded package is private, but
// an invalid name still breaks installs.
export function validateAppName(name: string): string | undefined {
  if (!/^[a-z0-9][a-z0-9._-]*$/.test(name)) {
    return (
      `invalid project name "${name}" — use lowercase letters, digits, ".", "-" or "_", ` +
      `starting with a letter or digit (e.g. "my-game")`
    );
  }
  return undefined;
}

function packageJsonTemplate(appName: string, arunaVersion: string): string {
  const manifest = {
    name: appName,
    private: true,
    type: "module",
    scripts: {
      dev: "aruna dev",
      build: "aruna build",
      check: "aruna check",
    },
    dependencies: {
      "@arunajs/aruna": `^${arunaVersion}`,
    },
    devDependencies: PINNED_TOOLCHAIN,
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function arunaConfigTemplate(): string {
  // entries: "generated" is the starter default (setup-dx Pillar 3): Aruna owns
  // the Script/LocalScript entry files, and optional hook modules customize
  // them. Everything else rides the recommended-layout conventions.
  return `import { defineConfig } from "aruna";

export default defineConfig({
  root: "src",
  entries: "generated",
});
`;
}

function gitignoreTemplate(): string {
  return `node_modules/
out/
include/

# Regenerated by \`aruna build\`; committing it also works — the build's owned-file
# ledger prunes stale artifacts either way.
src/.aruna/

*.rbxl
*.rbxlx
*.rbxl.lock
*.rbxlx.lock
`;
}

function rokitTemplate(): string {
  return `# Tools managed by Rokit (https://github.com/rojo-rbx/rokit).
# \`aruna dev\` spawns \`rojo serve\` from here.

[tools]
rojo = "${ROKIT_ROJO_SPEC}"
`;
}

function vscodeSettingsTemplate(): string {
  const settings = {
    "typescript.tsdk": "node_modules/typescript/lib",
    "typescript.enablePromptUseWorkspaceTsdk": true,
    "files.exclude": {
      out: true,
      include: true,
    },
  };
  return `${JSON.stringify(settings, null, 2)}\n`;
}

function readmeTemplate(appName: string): string {
  return `# ${appName}

A Roblox game built with [Aruna](https://github.com/astra-void/aruna) and roblox-ts.

## Daily loop

\`\`\`sh
npm run dev
\`\`\`

One terminal: rebuilds (codegen + Luau) on every save and serves the place to
Roblox Studio through \`rojo serve\` (install rojo with
[rokit](https://github.com/rojo-rbx/rokit): \`rokit install\`). In Studio, connect
via the Rojo plugin and hit Play.

## Project layout

- \`src/domains/<name>/\` — one folder per feature: \`schema.ts\` + \`model.ts\`
  (shared), \`actions.ts\` (server), \`ui.tsx\` (client). Each concern also has a
  folder form (\`actions/\`, \`ui/\`, ...), and a domain can carry its own
  \`server/\` and \`client/\` folders — those two are private to the domain, so
  other domains import its root modules (or only its \`index.ts\`, if it has one).
- \`src/shared/\`, \`src/server/\`, \`src/client/\` — classified by directory.
- \`src/.aruna/\` — generated: action stubs, entry scripts, vendored runtime.

Scaffold a new feature with \`npx aruna add domain <name>\`, then just save —
the dev loop regenerates the stubs. \`npx aruna doctor\` diagnoses setup issues.
`;
}

export type ScaffoldFile = {
  readonly name: string;
  readonly contents: string;
};

// The files create-aruna-app writes itself. Everything the aruna CLI can generate
// (tsconfig, rojo project, generated dir, the example domain) is delegated to
// `aruna init` / `aruna add` / `aruna build` post-install so there is a single
// source of truth for those shapes.
export function planScaffoldFiles(appName: string, arunaVersion: string): ScaffoldFile[] {
  return [
    { name: "package.json", contents: packageJsonTemplate(appName, arunaVersion) },
    { name: "aruna.config.ts", contents: arunaConfigTemplate() },
    { name: ".gitignore", contents: gitignoreTemplate() },
    { name: "rokit.toml", contents: rokitTemplate() },
    { name: ".vscode/settings.json", contents: vscodeSettingsTemplate() },
    { name: "README.md", contents: readmeTemplate(appName) },
  ];
}

// The aruna CLI invocations that complete the project after install, in order.
// Kept as data so the CLI can run them or print them as next steps.
export const POST_INSTALL_ARUNA_STEPS: ReadonlyArray<{
  args: readonly string[];
  description: string;
}> = [
  { args: ["init"], description: "scaffold tsconfig.json and default.project.json" },
  { args: ["add", "domain", "shop", "--with", "ui"], description: "scaffold the example domain" },
  { args: ["build"], description: "generate stubs, vendor the runtime, compile to Luau" },
];

export type ScaffoldResult = {
  readonly appDirectory: string;
  readonly created: string[];
};

export function scaffoldProject(options: {
  readonly appDirectory: string;
  readonly appName: string;
  readonly arunaVersion: string;
}): ScaffoldResult {
  fs.mkdirSync(options.appDirectory, { recursive: true });
  const existing = fs.readdirSync(options.appDirectory).filter((name) => name !== ".git");
  if (existing.length > 0) {
    throw new Error(
      `target directory ${options.appDirectory} is not empty — refusing to scaffold over existing files`,
    );
  }

  const created: string[] = [];
  for (const file of planScaffoldFiles(options.appName, options.arunaVersion)) {
    const absolute = path.join(options.appDirectory, file.name);
    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    fs.writeFileSync(absolute, file.contents, "utf8");
    created.push(file.name);
  }

  return { appDirectory: options.appDirectory, created };
}

// The aruna bin installed into the scaffolded project (via @arunajs/aruna's
// `bin` field). Used instead of `<pm> exec` so the invocation is identical
// across package managers.
export function localArunaBin(appDirectory: string): string {
  const binName = process.platform === "win32" ? "aruna.cmd" : "aruna";
  return path.join(appDirectory, "node_modules", ".bin", binName);
}
