use crate::actions::ArunaActionRecord;
use crate::diagnostics::{create_diagnostic, ArunaDiagnostic};
use crate::files::normalize_path;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::path::{Component, Path, PathBuf};

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GeneratedActionOutput {
    pub files: Vec<GeneratedFile>,
    pub diagnostics: Vec<ArunaDiagnostic>,
}

fn sanitize_identifier(input: &str) -> String {
    let mut output = String::new();

    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            output.push(ch);
        } else {
            output.push('_');
        }
    }

    if output.is_empty() {
        output.push('_');
    }

    if output
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        output.insert(0, '_');
    }

    output
}

fn relative_path(from_file: &str, to_file: &str) -> String {
    let from_dir = Path::new(from_file).parent().unwrap_or_else(|| Path::new(""));
    let from_components: Vec<Component<'_>> = from_dir.components().collect();
    let to_components: Vec<Component<'_>> = Path::new(to_file).components().collect();
    let common = from_components
        .iter()
        .zip(&to_components)
        .take_while(|(left, right)| left == right)
        .count();

    let mut relative = PathBuf::new();
    for _ in common..from_components.len() {
        relative.push("..");
    }
    for component in &to_components[common..] {
        match component {
            Component::Normal(part) => relative.push(part),
            Component::CurDir => {}
            Component::ParentDir => relative.push(".."),
            Component::RootDir => {}
            Component::Prefix(prefix) => relative.push(prefix.as_os_str()),
        }
    }

    let text = normalize_path(&relative.to_string_lossy());
    if text.is_empty() {
        ".".to_string()
    } else {
        text
    }
}

fn generated_file_path(generated_dir: &str, filename: &str) -> String {
    normalize_path(&Path::new(generated_dir).join(filename).to_string_lossy())
}

fn action_import_alias(action: &ArunaActionRecord) -> String {
    let source_without_extension = Path::new(&action.file).with_extension("");
    let source_text = normalize_path(&source_without_extension.to_string_lossy());
    format!(
        "{}_{}",
        sanitize_identifier(&source_text),
        sanitize_identifier(&action.export_name)
    )
}

fn client_stub_line(action: &ArunaActionRecord) -> String {
    format!(
        "export const {} = (input: unknown): Promise<unknown> => {{\n  return invokeAction(\"{}\", input);\n}};",
        action.export_name, action.id
    )
}

fn render_client_file(generated_dir: &str, actions: &[ArunaActionRecord]) -> GeneratedFile {
    let path = generated_file_path(generated_dir, "actions.client.generated.ts");
    let mut lines = vec![
        "// Generated by Aruna. Do not edit by hand.".to_string(),
        "// Source: Aruna action manifest v1".to_string(),
        "".to_string(),
        "import { invokeAction } from \"aruna/client-runtime\";".to_string(),
        "".to_string(),
    ];

    let mut seen_export_names = BTreeSet::new();
    for action in actions {
        if !seen_export_names.insert(action.export_name.clone()) {
            continue;
        }

        lines.push(client_stub_line(action));
        lines.push(String::new());
    }

    if lines.last().is_some_and(|line| line.is_empty()) {
        lines.pop();
    }

    GeneratedFile {
        path,
        contents: format!("{}\n", lines.join("\n")),
    }
}

fn render_server_file(generated_dir: &str, actions: &[ArunaActionRecord]) -> GeneratedFile {
    let path = generated_file_path(generated_dir, "actions.server.generated.ts");
    let mut lines = vec![
        "// Generated by Aruna. Do not edit by hand.".to_string(),
        "// Source: Aruna action manifest v1".to_string(),
        "".to_string(),
    ];

    for action in actions {
        let import_path = relative_path(
            &path,
            &normalize_path(&Path::new(&action.file).with_extension("").to_string_lossy()),
        );
        lines.push(format!(
            "import {{ {} as {} }} from \"{}\";",
            action.export_name,
            action_import_alias(action),
            import_path
        ));
    }

    if !actions.is_empty() {
        lines.push(String::new());
    }

    lines.push("export const actions = {".to_string());
    for action in actions {
        lines.push(format!(
            "  \"{}\": {},",
            action.id,
            action_import_alias(action)
        ));
    }
    lines.push("} as const;".to_string());

    GeneratedFile {
        path,
        contents: format!("{}\n", lines.join("\n")),
    }
}

fn duplicate_export_diagnostic(
    action: &ArunaActionRecord,
    previous_file: &str,
) -> ArunaDiagnostic {
    create_diagnostic(
        "aruna::557",
        format!(
            "Generated action export name {} is used by more than one action.",
            action.export_name
        ),
        Some(action.file.clone()),
        None,
        Some(format!(
            "First defined in {}, then again in {}.",
            previous_file, action.file
        )),
        Some(
            "Rename one action export or import the generated action through a namespaced layout in a future release."
                .to_string(),
        ),
    )
}

pub fn generate_action_files(
    generated_dir: &str,
    actions: &[ArunaActionRecord],
) -> GeneratedActionOutput {
    let mut diagnostics = Vec::new();
    let mut unique_client_actions = Vec::new();
    let mut seen_export_names = BTreeSet::new();
    let mut previous_export_files: std::collections::BTreeMap<String, String> =
        std::collections::BTreeMap::new();

    for action in actions {
        if let Some(previous_file) = previous_export_files.get(action.export_name.as_str()) {
            diagnostics.push(duplicate_export_diagnostic(action, previous_file));
            continue;
        }

        previous_export_files.insert(action.export_name.clone(), action.file.clone());
        if seen_export_names.insert(action.export_name.clone()) {
            unique_client_actions.push(action.clone());
        }
    }

    GeneratedActionOutput {
        files: vec![
            render_client_file(generated_dir, &unique_client_actions),
            render_server_file(generated_dir, actions),
        ],
        diagnostics,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn action(id: &str, file: &str, export_name: &str) -> ArunaActionRecord {
        ArunaActionRecord {
            id: id.to_string(),
            file: file.to_string(),
            export_name: export_name.to_string(),
            has_input_schema: false,
            has_output_schema: false,
            has_run: true,
            input_schema: None,
            output_schema: None,
        }
    }

    #[test]
    fn renders_deterministic_generated_files() {
        let actions = vec![
            action("inventory.restockItem", "src/domains/inventory/actions.ts", "restockItem"),
            action("shop.purchaseItem", "src/domains/shop/actions.ts", "purchaseItem"),
        ];

        let output = generate_action_files("src/.aruna", &actions);

        assert!(output.diagnostics.is_empty());
        assert_eq!(output.files.len(), 2);
        assert_eq!(output.files[0].path, "src/.aruna/actions.client.generated.ts");
        assert_eq!(output.files[1].path, "src/.aruna/actions.server.generated.ts");
        assert!(output.files[0]
            .contents
            .contains("invokeAction(\"inventory.restockItem\", input);"));
        assert!(output.files[0]
            .contents
            .contains("invokeAction(\"shop.purchaseItem\", input);"));
        assert!(output.files[1]
            .contents
            .contains("import { restockItem as src_domains_inventory_actions_restockItem } from \"../domains/inventory/actions\";"));
        assert!(output.files[1]
            .contents
            .contains("import { purchaseItem as src_domains_shop_actions_purchaseItem } from \"../domains/shop/actions\";"));
        assert!(output.files[1]
            .contents
            .contains("\"inventory.restockItem\": src_domains_inventory_actions_restockItem,"));
        assert!(output.files[1]
            .contents
            .contains("\"shop.purchaseItem\": src_domains_shop_actions_purchaseItem,"));
    }

    #[test]
    fn reports_duplicate_generated_action_exports() {
        let actions = vec![
            action("inventory.restockItem", "src/domains/inventory/actions.ts", "purchaseItem"),
            action("shop.purchaseItem", "src/domains/shop/actions.ts", "purchaseItem"),
        ];

        let output = generate_action_files("src/.aruna", &actions);

        assert_eq!(output.diagnostics.len(), 1);
        assert_eq!(output.diagnostics[0].code, "aruna::557");
        assert!(output.files[0].contents.contains("export const purchaseItem"));
        assert!(output
            .files[0]
            .contents
            .contains("invokeAction(\"inventory.restockItem\", input);"));
        assert!(!output.files[0].contents.contains("shop.purchaseItem"));
        assert!(output.files[1].contents.contains("inventory.restockItem"));
        assert!(output.files[1].contents.contains("shop.purchaseItem"));
    }
}
